/* Generates supabase/seed.sql from the current mock data (single source of
 * truth in src/data/*). Run: `npx tsx scripts/gen-seed.ts > supabase/seed.sql`.
 * Re-run whenever the mock data changes. Uses upserts, so it's safe to re-apply.
 */
import { NEIGHBORHOODS } from "../src/data/cities";
import { SPOTS } from "../src/data/spots";
import { GEHEIMTIPP_BY_CITY } from "../src/data/user";

const q = (s: string) => "'" + String(s).replace(/'/g, "''") + "'";
const nul = (v: string | undefined | null) => (v == null ? "null" : q(v));
const arr = (a: string[]) => "array[" + a.map(q).join(",") + "]::text[]";
const jsonb = (o: unknown) =>
  o == null ? "null" : "'" + JSON.stringify(o).replace(/'/g, "''") + "'::jsonb";

let out = "-- GENERATED by scripts/gen-seed.ts — do not edit by hand.\n";
out += "-- Run after 0001_init.sql (Supabase SQL editor bypasses RLS).\n\n";

for (const n of NEIGHBORHOODS) {
  out +=
    `insert into neighborhoods (city,name,blurb,blurb_de) values (` +
    `${q(n.city)},${q(n.name)},${q(n.blurb)},${nul(n.blurbDe)})` +
    ` on conflict (city,name) do update set blurb=excluded.blurb, blurb_de=excluded.blurb_de;\n`;
}
out += "\n";

for (const s of SPOTS) {
  out +=
    `insert into spots (id,name,category,city,neighborhood,hook,image_note,description,tags,price_level,address,ambience,rating,lat,lng,tone,reserve_url,hours,date_label,meeting_point,ticket_url,de) values (` +
    [
      q(s.id), q(s.name), q(s.category), q(s.city), q(s.neighborhood),
      q(s.hook), q(s.imageNote), q(s.description), arr(s.tags), String(s.priceLevel),
      q(s.address), arr(s.ambience), String(s.rating), String(s.lat), String(s.lng),
      q(s.tone), nul(s.reserveUrl), jsonb(s.hours), nul(s.dateLabel),
      nul(s.meetingPoint), nul(s.ticketUrl), jsonb(s.de),
    ].join(",") +
    `) on conflict (id) do update set name=excluded.name, category=excluded.category, city=excluded.city, neighborhood=excluded.neighborhood, hook=excluded.hook, image_note=excluded.image_note, description=excluded.description, tags=excluded.tags, price_level=excluded.price_level, address=excluded.address, ambience=excluded.ambience, rating=excluded.rating, lat=excluded.lat, lng=excluded.lng, tone=excluded.tone, reserve_url=excluded.reserve_url, hours=excluded.hours, date_label=excluded.date_label, meeting_point=excluded.meeting_point, ticket_url=excluded.ticket_url, de=excluded.de;\n`;
}
out += "\n";

for (const [city, g] of Object.entries(GEHEIMTIPP_BY_CITY)) {
  if (!g) continue;
  out +=
    `insert into geheimtipp_by_city (city,spot_id,week_label,teaser,teaser_de) values (` +
    `${q(city)},${q(g.spotId)},${q(g.weekLabel)},${q(g.teaser)},${nul(g.teaserDe)})` +
    ` on conflict (city) do update set spot_id=excluded.spot_id, week_label=excluded.week_label, teaser=excluded.teaser, teaser_de=excluded.teaser_de;\n`;
}

process.stdout.write(out);
